# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # keep your service names short
    app.github_api:
        class: AppBundle\Utils\GitHubApi
        arguments: ["@service_container"]

    app.contributor_relation_service:
        class: AppBundle\Utils\ContributorRelationService
        arguments: ["@service_container"]